Fix syntax error on ng build --prod ERROR in ..\..\app\catalog\catalog.component.html(5,55): : Property 'categories'  does not exist on type 'CatalogComponent'.